### ISSUE TITLE
Fix mixed content warning in Chrome

### ISSUE THREAD

**Issue by kristovatlas** [kiarafrobles/kiarafrobles.github.io#1]
In _layouts/default.html:23:

Change:
`    <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700' rel='stylesheet' type='text/css'>`

To:
`    <link href='https://fonts.googleapis.com/css?family=PT+Sans:400,700' rel='stylesheet' type='text/css'>`

**Comment by kiarafrobles** [comment]
Wow, this took me a while to see! Layout changed.
